//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_LoginForm.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BetCredit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BetCredit()
        {
            this.CreditContract = new HashSet<CreditContract>();
        }
    
        public byte Id { get; set; }
        public byte IdSummCredit { get; set; }
        public decimal Bet { get; set; }
        public byte IdTermCredit { get; set; }
    
        public virtual SummCredit SummCredit { get; set; }
        public virtual TermCredit TermCredit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CreditContract> CreditContract { get; set; }
    }
}
