//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_LoginForm.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComissionByInvestment
    {
        public byte Id { get; set; }
        public byte IdComission { get; set; }
        public byte IdInvestment { get; set; }
        public decimal Procent { get; set; }
    
        public virtual Comission Comission { get; set; }
        public virtual Investment Investment { get; set; }
    }
}
