//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_LoginForm.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditContract
    {
        public int Id { get; set; }
        public int IdContract { get; set; }
        public byte IdCredit { get; set; }
        public byte IdBetCredit { get; set; }
    
        public virtual BetCredit BetCredit { get; set; }
        public virtual Contract Contract { get; set; }
        public virtual Credit Credit { get; set; }
    }
}
