//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_LoginForm.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepositContract
    {
        public int Id { get; set; }
        public int IdContract { get; set; }
        public byte IdDeposit { get; set; }
        public byte IdBetDeposit { get; set; }
        public int SumDeposit { get; set; }
    
        public virtual BetDeposit BetDeposit { get; set; }
        public virtual Contract Contract { get; set; }
        public virtual Deposit Deposit { get; set; }
    }
}
