//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_LoginForm.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InsuranceContract
    {
        public int Id { get; set; }
        public int IdContract { get; set; }
        public byte IdInsurance { get; set; }
        public byte IdSummInsurance { get; set; }
    
        public virtual Contract Contract { get; set; }
        public virtual Insurance Insurance { get; set; }
        public virtual SummInsurance SummInsurance { get; set; }
    }
}
