//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_LoginForm.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvestmentContract
    {
        public int Id { get; set; }
        public int IdContract { get; set; }
        public byte IdInvestment { get; set; }
        public byte IdBetInvestment { get; set; }
    
        public virtual BetInvestment BetInvestment { get; set; }
        public virtual Contract Contract { get; set; }
        public virtual Investment Investment { get; set; }
    }
}
