//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_LoginForm.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Investment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Investment()
        {
            this.ComissionByInvestments = new HashSet<ComissionByInvestment>();
            this.InvestmentContracts = new HashSet<InvestmentContract>();
        }
    
        public byte Id { get; set; }
        public string Name { get; set; }
        public byte IdRiskLevel { get; set; }
        public byte IdDirection { get; set; }
        public int MinimalContribution { get; set; }
        public string NameOfIndustries { get; set; }
        public string NameOfCompanies { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComissionByInvestment> ComissionByInvestments { get; set; }
        public virtual InvestmentDirection InvestmentDirection { get; set; }
        public virtual InvestmentRiskLevel InvestmentRiskLevel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvestmentContract> InvestmentContracts { get; set; }
    }
}
