//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_LoginForm.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_BANK4Entities1 : DbContext
    {
        private static DB_BANK4Entities1 _context;

        public DB_BANK4Entities1()
            : base("name=DB_BANK4Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public static DB_BANK4Entities1 GetContext()
        {
            if (_context == null)
                _context = new DB_BANK4Entities1();

            return _context;
        }

        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<BetCredit> BetCredits { get; set; }
        public virtual DbSet<BetDeposit> BetDeposits { get; set; }
        public virtual DbSet<BetInvestment> BetInvestments { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<ClientInfo> ClientInfoes { get; set; }
        public virtual DbSet<Comission> Comissions { get; set; }
        public virtual DbSet<ComissionByInvestment> ComissionByInvestments { get; set; }
        public virtual DbSet<Contract> Contracts { get; set; }
        public virtual DbSet<Credit> Credits { get; set; }
        public virtual DbSet<CreditContract> CreditContracts { get; set; }
        public virtual DbSet<Deposit> Deposits { get; set; }
        public virtual DbSet<DepositContract> DepositContracts { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Insurance> Insurances { get; set; }
        public virtual DbSet<InsuranceContract> InsuranceContracts { get; set; }
        public virtual DbSet<Investment> Investments { get; set; }
        public virtual DbSet<InvestmentContract> InvestmentContracts { get; set; }
        public virtual DbSet<InvestmentDirection> InvestmentDirections { get; set; }
        public virtual DbSet<InvestmentRiskLevel> InvestmentRiskLevels { get; set; }
        public virtual DbSet<Post> Posts { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Score> Scores { get; set; }
        public virtual DbSet<SummCredit> SummCredits { get; set; }
        public virtual DbSet<SummInsurance> SummInsurances { get; set; }
        public virtual DbSet<TermCredit> TermCredits { get; set; }
        public virtual DbSet<TermDeposit> TermDeposits { get; set; }
        public virtual DbSet<TermInsurance> TermInsurances { get; set; }
        public virtual DbSet<TermInvestment> TermInvestments { get; set; }
        public virtual DbSet<TypeClient> TypeClients { get; set; }
        public virtual DbSet<TypeScore> TypeScores { get; set; }
    }
}
