//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_LoginForm.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_BANK3Entities : DbContext
    {
        private static DB_BANK3Entities _context;
        public DB_BANK3Entities()
            : base("name=DB_BANK3Entities")
        {
        }

        public static DB_BANK3Entities GetContext()
        {
            if (_context == null)
                _context = new DB_BANK3Entities();

            return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<BetCredit> BetCredit { get; set; }
        public virtual DbSet<BetDeposit> BetDeposit { get; set; }
        public virtual DbSet<BetInvestment> BetInvestment { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<ClientInfo> ClientInfo { get; set; }
        public virtual DbSet<Comission> Comission { get; set; }
        public virtual DbSet<ComissionByInvestment> ComissionByInvestment { get; set; }
        public virtual DbSet<Contract> Contract { get; set; }
        public virtual DbSet<Credit> Credit { get; set; }
        public virtual DbSet<CreditContract> CreditContract { get; set; }
        public virtual DbSet<Deposit> Deposit { get; set; }
        public virtual DbSet<DepositContract> DepositContract { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Insurance> Insurance { get; set; }
        public virtual DbSet<InsuranceContract> InsuranceContract { get; set; }
        public virtual DbSet<Investment> Investment { get; set; }
        public virtual DbSet<InvestmentContract> InvestmentContract { get; set; }
        public virtual DbSet<InvestmentDirection> InvestmentDirection { get; set; }
        public virtual DbSet<InvestmentRiskLevel> InvestmentRiskLevel { get; set; }
        public virtual DbSet<Post> Post { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Score> Score { get; set; }
        public virtual DbSet<SummCredit> SummCredit { get; set; }
        public virtual DbSet<SummInsurance> SummInsurance { get; set; }
        public virtual DbSet<TermCredit> TermCredit { get; set; }
        public virtual DbSet<TermDeposit> TermDeposit { get; set; }
        public virtual DbSet<TermInsurance> TermInsurance { get; set; }
        public virtual DbSet<TermInvestment> TermInvestment { get; set; }
        public virtual DbSet<TypeClient> TypeClient { get; set; }
        public virtual DbSet<TypeScore> TypeScore { get; set; }
    }
}
